import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

type LanguageType = 'en' | 'hi' | 'pa' | 'gu' | 'mr' | 'ta' | 'te';

interface LanguageContextType {
    language: LanguageType;
    setLanguage: (lang: LanguageType) => void;
    t: (key: string, params?: Record<string, any>) => string;
}

const translations: Record<LanguageType, Record<string, string>> = {
    en: {
        settings: 'Settings',
        manage_account: 'Manage your account and preferences',
        app_features: 'App Features',
        select_language: 'Select Language',
        kot_tables: 'KOT & Tables',
        kitchen_orders: 'Kitchen Order Tickets (KOT), Table booking',
        change_language_desc: 'Change app language to Hindi, English, etc.',
        success_update: 'updated successfully!',
        done: 'Done',
        menu: 'Menu',
        orders: 'Orders',
        dashboard: 'Dashboard',
        printer: 'Printer',
        client: 'Clients',
        add_item: 'Add Item',
        total: 'Total',
        cart: 'Cart',
        checkout: 'Checkout',
        paying: 'Paying',
        received: 'Received',
        cash: 'Cash',
        upi: 'UPI',
        card: 'Card',
        items: 'Items',
        price: 'Price',
        quantity: 'Quantity',
        bill: 'Bill',
        save: 'Save',
        print: 'Print',
        hold: 'Hold',
        clear: 'Clear',
        loading: 'Loading...',
        no_items: 'No items found',
        search: 'Search...',
        live_orders: 'Live Orders',
        tap_table: 'Tap a table to manage its orders',
        add_table: 'Add Table',
        active_orders: 'Active Orders',
        no_active_orders: 'No Active Orders',
        quick_add_table: 'Quick Add Table',
        table_name: 'Table Name',
        cancel: 'Cancel',
        create: 'Create',
        sales_summary: 'Sales Summary',
        today: 'Today',
        weekly: 'Weekly',
        monthly: 'Monthly',
        analytics_reports: 'Analytics & Reports',
        daily_sales: 'Daily Sales',
        weekly_sales: 'Weekly Sales',
        monthly_sales: 'Monthly Sales',
        bill_records: 'Bill Records',
        performance: 'today\'s performance',
        trends: '7-day revenue trends',
        growth: 'Monthly growth overview',
        invoices: 'All historical invoices',
        parties: 'PARTIES',
        categories: 'CATEGORIES',
        add_customer: 'ADD CUSTOMER',
        no_customers: 'No customers found',
        regular_billing: 'Regular billing',
        address: 'Billing Address',
        balance: 'Current Balance',
        call: 'Call',
        whatsapp: 'WhatsApp',
        regular: 'REGULAR',
        welcome_guest: 'WELCOME GUEST',
        hi: 'Hi',
        home: 'Home',
        home_menu: 'Home Menu',
        table_qr_codes: 'Table QR Codes',
        edit_menu_item: 'Edit Menu Item',
        sign_in: 'Sign In',
        sign_out: 'Sign Out',
        edit_item: 'Edit Item',
        add_new_item: 'Add New Item',
        add_category: 'Add Category',
        items_list: 'Items List',
        qr_header: 'Table QR Codes',
        business_name: 'Business Name',
        business_address: 'Business Address',
        gst_number: 'GST Number',
        save_profile: 'Save Profile',
        profile_saved: 'Profile Saved!',
        daily_report: 'Daily Sales Report',
        weekly_report: 'Weekly Sales Report',
        monthly_report: 'Monthly Sales Report',
        all_transactions: 'All Transactions',
        hold_orders: 'Hold Orders',
        no_hold_orders: 'No hold orders',
        bill_details: 'Bill Details',
        print_bill: 'Print Bill',
        gst_vat: 'GST/VAT',
        discounts: 'Discounts',
        app_features_desc: 'Manage all app features here',
        bill_branding: 'Branding to your bills',
        qr_menu: 'QR Menu',
        manage_live_orders: 'Manage live orders',
        edit_profile: 'Edit Business Profile',
        create_profile: 'Create Business Profile',
        setup_profile: 'Set up your professional business profile',
        bills_transactions: 'Bills & Transactions',
        gst_vat_discounts: 'GST/VAT & Discounts',
        business_profile: 'Business Profile',
        advance_loyalty: 'Advance Loyalty',
        points_system: 'Points system, Customer loyalty',
        kot_billing: 'KOT & Billing',
        edit_category: 'Edit Item Category',
        add_image: 'Add Image',
        item_name: 'Item Name',
        select_categories: 'Select Category',
        update_item: 'Update Item',
        category_created: 'Category Created!',
        added_success: 'New category has been added.',
        item_updated: 'Item Updated!',
        changes_saved: 'Changes saved successfully.',
        item_deleted: 'Item Deleted!',
        item_removed: 'Item has been removed.',
        delete_item_confirm: 'Delete Item?',
        delete_confirm_desc: 'Are you sure you want to delete this item? This cannot be undone.',
        update_details: 'Update Details',
        category_updated: 'Category Updated!',
        category_deleted: 'Category Deleted!',
        manage_tables_desc: 'Manage your dining tables and QR codes',
        live_qr: 'Live QR',
        no_tables: 'No tables created yet.',
        add_new_table: 'Add New Table',
        scan_to_view_menu: 'Scan to View Menu',
        qr_instructions: 'Let customers scan this to see your live menu and place orders.',
        download_qr: 'Download QR',
        save_table: 'Save Table',
        professional_menu_desc: "Let's build your professional menu",
        fill_details_desc: 'Fill in the details below to add a new item to your menu.',
        item_image: 'Item Image',
        image_preview: 'Image Preview',
        no_image_selected: 'No Image Selected',
        save_item: 'Save Item',
        order: 'Order',
        orders_saved: 'orders saved',
        no_hold_orders_desc: 'No hold orders',
        deleted_successfully: 'Deleted Successfully!',
        order_removed_desc: 'Order has been removed from the list.',
        delete_order_confirm: 'Delete Order?',
        delete_order_desc: 'This order will be permanently deleted. This action cannot be undone.',
        yes_delete_order: 'Yes, Delete Order',
        order_resumed: 'Order Resumed!',
        loading_cart_desc: 'Loading into active cart...',
        resume_order_confirm: 'Resume Order?',
        resume_order_desc: 'This order will be loaded back into your active cart.',
        order_ready_resume: 'item ready to resume',
        active_cart_replace_desc: 'Active cart items will be replaced. Only this order will be loaded.',
        yes_resume_order: 'Yes, Resume Order',
        delete_multiple_confirm: 'Delete {count} Orders?',
        bulk_delete_desc: 'All selected orders will be permanently deleted. This action cannot be undone.',
        orders_selected: 'Orders Selected',
        yes_delete_selected: 'Yes, Delete All Selected',
        orders_removed: 'orders have been removed.',
        cleared: 'Cleared!',
        form_reset_desc: 'Form has been reset successfully.',
        reset_form: 'Reset Form?',
        clear_confirm_desc: 'Are you sure you want to clear all item details?',
        clear_all: 'Clear All',
        try_again: 'Try Again',
        select_category_desc: 'Select a category for your item',
        item: 'item',
        name_missing: 'Name Missing!',
        enter_category_name: 'Please enter category name',
        category_saved: 'Category Saved!',
        category_name: 'Category Name',
        category_hint: 'Items are shown by category while entering orders',
        all_categories_label: 'ALL CATEGORIES',
        none: 'None',
        save_and_new: 'Save & New',
        save_category: 'Save Category',
        cart_empty: '🛒 Cart empty!',
        printing_failed: '❌ Printing failed',
        billing_dashboard: 'Billing Dashboard',
        customer_details: 'Customer Details',
        select_existing_customer: 'Select Existing Customer',
        customer_name: 'Customer Name',
        phone: 'Phone',
        save_customer: 'Save Customer',
        cart_summary: 'Cart Summary',
        discount: 'Discount',
        service_charge: 'Service charge',
        total_due: 'Total Due',
        print_save_bill: 'PRINT & SAVE BILL',
        clear_cart: 'Clear Cart',
        bill_saved: 'Bill Saved!',
        bill_saved_desc: 'Your bill has been successfully printed and saved.',
        missing_info: 'Missing Info',
        missing_info_desc: 'Please select or add a customer detail first to continue billing.',
        missing_fields: 'Missing Fields',
        missing_fields_desc: "Please enter the customer's name and phone number to save.",
        success: 'Success!',
        customer_saved_desc: 'Customer details have been saved successfully.',
        dismiss: 'DISMISS',
        duplicate_record_found: 'Duplicate Record Found',
        phone_already_exists_desc: 'This phone number is already registered in your database. Please search for the existing customer instead.',
        boost_sales: 'Boost Your Sales!',
        setup_profile_desc: 'Set up your professional business profile to add branding to your bills and QR codes.',
        professional_identity: 'Your professional identity on Kravy',
        business_identity: 'Business Identity',
        type: 'Type',
        gstin: 'GSTIN',
        not_provided: 'Not Provided',
        contact_info: 'Contact Information',
        person: 'Person',
        email: 'Email',
        location_pay: 'Location & Pay',
        upi_id: 'UPI ID',
        public_link: 'Public Link',
        authorized_signature: 'Authorized Signature',
        state: 'State',
        bills: 'Bills',
        total_sales_label: 'Total Sales',
        sales: 'Sales',
        no_sales_found_table: 'No sales found for Table View.',
        daily_sales_report: 'Daily Sales Report',
        all_time_sales: 'All Time Sales',
        table_view: 'Table View',
        card_view: 'Card View',
        no_sales_records: 'No sales records found yet.',
        weekly_sales_report: 'Weekly Sales Report',
        monthly_sales_report: 'Monthly Sales Report',
        weekly_sales_label: 'Weekly Sales',
        week: 'Week',
        no_sales_found_weekly: 'No weekly sales found for Table View.',
        bills_count: 'Bills Count',
        month: 'Month',
        no_sales_found_monthly: 'No monthly sales found for Table View.',
        all_time_revenue: 'All Time Revenue',
        pending: 'PENDING',
        preparing: 'PREPARING',
        served: 'SERVED',
        prepare: 'Prepare',
        mark_served: 'Mark Served',
        table_orders: 'Table Orders',
        table_orders_desc: 'Manage live orders from QR Menu',
        gst_tax_settings: 'GST / TAX SETTINGS',
        enable_global_gst: 'Enable Global GST System',
        gst_add_desc: '{rate}% GST will be added to every order',
        per_product_gst: 'Per-Product GST',
        default_gst_desc: 'Always use Default GST for all products',
        quick_select_rate: 'QUICK SELECT RATE',
        custom_rate: 'CUSTOM RATE (%)',
        enable_discounts_label: 'Enable discounts',
        allow_discount_desc: 'Allow discount fields while creating bills',
        default_discount_label: 'Default discount rate',
        discount_rate: 'Discount rate',
        enable_service_charge_label: 'Enable service charges',
        service_charge_desc: 'Add service charge to bills (e.g., delivery)',
        default_service_charge_label: 'Default service charge',
        kot_feature_title: 'KOT (Kitchen Order Ticket)',
        kot_feature_desc: 'Manage KOT billing and table booking features',
        enable_kot_billing: 'Enable KOT Billing',
        enable_kot_desc: 'Allow generating Kitchen Order Tickets for quick orders',
        enable_table_booking: 'Enable Table Booking',
        enable_table_booking_desc: 'Assign table numbers to KOT orders',
        kot_info_text: 'KOT button will appear in Quick Bill screen. Use it to print kitchen orders before final billing.',
        item_name_placeholder: 'e.g. Burger, Pizza...',
        choose_category: 'Choose Category',
        select_category_for_item: 'Select a category for your item',
        no_categories_found: 'No categories found in menu.',
        item_added_desc: 'Item has been added to the menu.',
        category_added_to_list: 'Category added to local list.',
        no_tables_created: 'No tables created yet',
        get_started_create_table: 'Get Started: Create Table',
    },
    hi: {
        settings: 'सेटिंग्स',
        manage_account: 'अपने खाते और प्राथमिकताओं को प्रबंधित करें',
        app_features: 'ऐप सुविधाएं',
        select_language: 'भाषा चुनें',
        kot_tables: 'KOT और टेबल',
        kitchen_orders: 'किचन ऑर्डर टिकट (KOT), टेबल बुकिंग',
        change_language_desc: 'ऐप की भाषा हिंदी, अंग्रेजी आदि में बदलें',
        success_update: 'सफलतापूर्वक अपडेट किया गया!',
        done: 'हो गया',
        menu: 'मेनू',
        orders: 'ऑर्डर',
        dashboard: 'डैशबोर्ड',
        printer: 'प्रिंटर',
        client: 'ग्राहक',
        add_item: 'आइटम जोड़ें',
        total: 'कुल',
        cart: 'कार्ट',
        checkout: 'चेकआउट',
        paying: 'भुगतान',
        received: 'प्राप्त',
        cash: 'नकद',
        upi: 'UPI',
        card: 'कार्ड',
        items: 'आइटम',
        price: 'कीमत',
        quantity: 'मात्रा',
        bill: 'बिल',
        save: 'सहेजें',
        print: 'प्रिंट',
        hold: 'होल्ड',
        clear: 'साफ करें',
        loading: 'लोड हो रहा है...',
        no_items: 'कोई आइटम नहीं मिला',
        search: 'खोजें...',
        live_orders: 'लाइव ऑर्डर',
        tap_table: 'ऑर्डर प्रबंधित करने के लिए टेबल पर टैप करें',
        add_table: 'टेबल जोड़ें',
        active_orders: 'सक्रिय ऑर्डर',
        no_active_orders: 'कोई सक्रिय ऑर्डर नहीं',
        quick_add_table: 'त्वरित टेबल जोड़ें',
        table_name: 'टेबल का नाम',
        cancel: 'रद्द करें',
        create: 'बनाएं',
        sales_summary: 'बिक्री सारांश',
        today: 'आज',
        weekly: 'साप्ताहिक',
        monthly: 'मासिक',
        analytics_reports: 'एनालिटिक्स और रिपोर्ट',
        daily_sales: 'दैनिक बिक्री',
        weekly_sales: 'साप्ताहिक बिक्री',
        monthly_sales: 'मासिक बिक्री',
        bill_records: 'बिल रिकॉर्ड',
        performance: 'आज का प्रदर्शन',
        trends: '7-दिन के रुझान',
        growth: 'मासिक विकास अवलोकन',
        invoices: 'सभी पुराने चालान',
        parties: 'पार्टियां',
        categories: 'श्रेणियां',
        add_customer: 'ग्राहक जोड़ें',
        no_customers: 'कोई ग्राहक नहीं मिला',
        regular_billing: 'नियमित बिलिंग',
        address: 'बिलिंग पता',
        balance: 'वर्तमान शेष',
        call: 'कॉल',
        whatsapp: 'व्हाट्सएप',
        regular: 'नियमित',
        welcome_guest: 'स्वागत है मेहमान',
        hi: 'नमस्ते',
        home: 'होम',
        home_menu: 'होम मेनू',
        table_qr_codes: 'टेबल QR कोड',
        edit_menu_item: 'मेनू आइटम एडिट करें',
        sign_in: 'साइन इन',
        sign_out: 'साइन आउट',
        edit_item: 'आइटम एडिट करें',
        add_new_item: 'नया आइटम जोड़ें',
        add_category: 'कैटेगरी जोड़ें',
        items_list: 'आइटम लिस्ट',
        qr_header: 'टेबल QR कोड',
        business_name: 'व्यापार का नाम',
        business_address: 'व्यापार का पता',
        gst_number: 'GST नंबर',
        save_profile: 'प्रोफाइल सहेजें',
        profile_saved: 'प्रोफाइल सेव हो गई!',
        daily_report: 'दैनिक बिक्री रिपोर्ट',
        weekly_report: 'साप्ताहिक बिक्री रिपोर्ट',
        monthly_report: 'मासिक बिक्री रिपोर्ट',
        all_transactions: 'सभी लेन-देन',
        hold_orders: 'होल्ड ऑर्डर',
        no_hold_orders: 'कोई होल्ड ऑर्डर नहीं',
        bill_details: 'बिल विवरण',
        print_bill: 'बिल प्रिंट करें',
        gst_vat: 'GST/VAT',
        discounts: 'छूट (Discounts)',
        app_features_desc: 'यहाँ ऐप की सभी सुविधाओं को प्रबंधित करें',
        bill_branding: 'अपने बिलों में ब्रांडिंग जोड़ें',
        qr_menu: 'QR मेनू',
        manage_live_orders: 'लाइव ऑर्डर प्रबंधित करें',
        edit_profile: 'बिजनेस प्रोफाइल एडिट करें',
        create_profile: 'बिजनेस प्रोफाइल बनाएं',
        setup_profile: 'अपना पेशेवर बिजनेस प्रोफाइल सेट करें',
        bills_transactions: 'बिल और लेनदेन',
        gst_vat_discounts: 'GST/VAT और छूट',
        business_profile: 'बिजनेस प्रोफाइल',
        advance_loyalty: 'एडवांस लॉयल्टी',
        points_system: 'पॉइंट्स सिस्टम, ग्राहक लॉयल्टी',
        kot_billing: 'KOT और बिलिंग',
        edit_category: 'आइटम कैटेगरी एडिट करें',
        add_image: 'फोटो जोड़ें',
        item_name: 'आइटम का नाम',
        select_categories: 'कैटेगरी चुनें',
        update_item: 'आइटम अपडेट करें',
        category_created: 'कैटेगरी बन गई!',
        added_success: 'नई कैटेगरी जोड़ दी गई है।',
        item_updated: 'आइटम अपडेट हो गया!',
        changes_saved: 'बदलाव सफलतापूर्वक सहेजे गए।',
        item_deleted: 'आइटम हटा दिया गया!',
        item_removed: 'आइटम सूची से हटा दिया गया है।',
        delete_item_confirm: 'आइटम हटाएं?',
        delete_confirm_desc: 'क्या आप वाकई इस आइटम को हटाना चाहते हैं? इसे वापस नहीं लिया जा सकता।',
        update_details: 'विवरण अपडेट करें',
        category_updated: 'कैटेगरी अपडेट हो गई!',
        category_deleted: 'कैटेगरी हटा दी गई!',
        manage_tables_desc: 'अपने डाइनिंग टेबल और QR कोड प्रबंधित करें',
        live_qr: 'लाइव QR',
        no_tables: 'अभी तक कोई टेबल नहीं बनाई गई है।',
        add_new_table: 'नई टेबल जोड़ें',
        scan_to_view_menu: 'मेनू देखने के लिए स्कैन करें',
        qr_instructions: 'ग्राहकों को अपना लाइव मेनू देखने और ऑर्डर देने के लिए इसे स्कैन करने दें।',
        download_qr: 'QR डाउनलोड करें',
        save_table: 'टेबल सहेजें',
        professional_menu_desc: "आइए आपका पेशेवर मेनू बनाएं",
        fill_details_desc: 'अपने मेनू में नया आइटम जोड़ने के लिए नीचे दिए गए विवरण भरें।',
        item_image: 'आइटम की फोटो',
        image_preview: 'फोटो का पूर्वावलोकन',
        no_image_selected: 'कोई फोटो नहीं चुनी गई',
        save_item: 'आइटम सहेजें',
        order: 'ऑर्डर',
        orders_saved: 'ऑर्डर सहेजे गए',
        no_hold_orders_desc: 'कोई होल्ड ऑर्डर नहीं',
        deleted_successfully: 'सफलतापूर्वक हटा दिया गया!',
        order_removed_desc: 'ऑर्डर सूची से हटा दिया गया है।',
        delete_order_confirm: 'ऑर्डर हटाएं?',
        delete_order_desc: 'यह ऑर्डर स्थायी रूप से हटा दिया जाएगा। इसे वापस नहीं लिया जा सकता।',
        yes_delete_order: 'हां, ऑर्डर हटाएं',
        order_resumed: 'ऑर्डर फिर से शुरू!',
        loading_cart_desc: 'सक्रिय कार्ट में लोड हो रहा है...',
        resume_order_confirm: 'ऑर्डर फिर से शुरू करें?',
        resume_order_desc: 'यह ऑर्डर आपकी सक्रिय कार्ट में वापस लोड हो जाएगा।',
        order_ready_resume: 'आइटम फिर से शुरू करने के लिए तैयार',
        active_cart_replace_desc: 'सक्रिय कार्ट आइटम बदल दिए जाएंगे। केवल यही ऑर्डर लोड होगा।',
        yes_resume_order: 'हां, ऑर्डर फिर से शुरू करें',
        delete_multiple_confirm: '{count} ऑर्डर हटाएं?',
        bulk_delete_desc: 'सभी चयनित ऑर्डर स्थायी रूप से हटा दिए जाएंगे। इसे वापस नहीं लिया जा सकता।',
        orders_selected: 'ऑर्डर चुने गए',
        yes_delete_selected: 'हां, सभी चयनित हटाएं',
        orders_removed: 'ऑर्डर हटा दिए गए हैं।',
        cleared: 'साफ किया गया!',
        form_reset_desc: 'फॉर्म सफलतापूर्वक रिसेट हो गया है।',
        reset_form: 'फॉर्म रिसेट करें?',
        clear_confirm_desc: 'क्या आप वाकई सभी आइटम विवरण साफ करना चाहते हैं?',
        clear_all: 'सब साफ करें',
        try_again: 'फिर कोशिश करें',
        select_category_desc: 'अपने आइटम के लिए कैटेगरी चुनें',
        item: 'आइटम',
        name_missing: 'नाम गायब है!',
        enter_category_name: 'कृपया कैटेगरी का नाम दर्ज करें',
        category_saved: 'कैटेगरी सहेजी गई!',
        category_name: 'कैटेगरी का नाम',
        category_hint: 'ओर्डर लेते समय आइटम कैटेगरी के आधार पर दिखाए जाते हैं',
        all_categories_label: 'सभी कैटेगरीज',
        none: 'कोई नहीं',
        save_and_new: 'सहेजें और नया',
        save_category: 'कैटेगरी सहेजें',
        cart_empty: '🛒 कार्ट खाली है!',
        printing_failed: '❌ प्रिंटिंग विफल रही',
        billing_dashboard: 'बिलिंग डैशबोर्ड',
        customer_details: 'ग्राहक विवरण',
        select_existing_customer: 'मौजूदा ग्राहक चुनें',
        customer_name: 'ग्राहक का नाम',
        phone: 'फोन नंबर',
        save_customer: 'ग्राहक सहेजें',
        cart_summary: 'कार्ट सारांश',
        discount: 'छूट',
        service_charge: 'सर्विस चार्ज',
        total_due: 'कुल देय',
        print_save_bill: 'बिल प्रिंट और सेव करें',
        clear_cart: 'कार्ट साफ करें',
        bill_saved: 'बिल सहेजा गया!',
        bill_saved_desc: 'आपका बिल सफलतापूर्वक प्रिंट और सहेज लिया गया है।',
        missing_info: 'जानकारी गायब है',
        missing_info_desc: 'बिलिंग जारी रखने के लिए कृपया पहले ग्राहक विवरण चुनें या जोड़ें।',
        missing_fields: 'विवरण भरें',
        missing_fields_desc: 'सहेजने के लिए कृपया ग्राहक का नाम और फोन नंबर दर्ज करें।',
        success: 'सफल!',
        customer_saved_desc: 'ग्राहक विवरण सफलतापूर्वक सहेजे गए हैं।',
        dismiss: 'खारिज करें',
        duplicate_record_found: 'डुप्लिकेट रिकॉर्ड मिला',
        phone_already_exists_desc: 'यह फोन नंबर पहले से ही आपके डेटाबेस में पंजीकृत है। कृपया इसके बजाय मौजूदा ग्राहक खोजें।',
        boost_sales: 'अपनी बिक्री बढ़ाएं!',
        setup_profile_desc: 'अपने बिलों और QR कोड में ब्रांडिंग जोड़ने के लिए अपना पेशेवर बिजनेस प्रोफाइल सेट करें।',
        professional_identity: 'Kravy पर आपकी पेशेवर पहचान',
        business_identity: 'व्यवसाय की पहचान',
        type: 'प्रकार',
        gstin: 'GSTIN',
        not_provided: 'उपलब्ध नहीं',
        contact_info: 'संपर्क विवरण',
        person: 'व्यक्ति',
        email: 'ईमेल',
        location_pay: 'स्थान और भुगतान',
        upi_id: 'UPI ID',
        public_link: 'सार्वजनिक लिंक',
        authorized_signature: 'अधिकृत हस्ताक्षर',
        state: 'राज्य',
        bills: 'बिल',
        total_sales_label: 'कुल बिक्री',
        sales: 'बिक्री',
        no_sales_found_table: 'टेबल व्यू के लिए कोई बिक्री नहीं मिली।',
        daily_sales_report: 'दैनिक बिक्री रिपोर्ट',
        all_time_sales: 'कुल बिक्री',
        table_view: 'टेबल व्यू',
        card_view: 'कार्ड व्यू',
        no_sales_records: 'अभी तक कोई बिक्री रिकॉर्ड नहीं मिला।',
        weekly_sales_report: 'साप्ताहिक बिक्री रिपोर्ट',
        monthly_sales_report: 'मासिक बिक्री रिपोर्ट',
        weekly_sales_label: 'साप्ताहिक बिक्री',
        week: 'सप्ताह',
        no_sales_found_weekly: 'टेबल व्यू के लिए कोई साप्ताहिक बिक्री नहीं मिली।',
        bills_count: 'बिलों की संख्या',
        month: 'महीना',
        no_sales_found_monthly: 'टेबल व्यू के लिए कोई मासिक बिक्री नहीं मिली।',
        all_time_revenue: 'कुल राजस्व',
        pending: 'पेंडिंग',
        preparing: 'तैयार हो रहा है',
        served: 'परोसा गया',
        prepare: 'बनाएं',
        mark_served: 'परोसा गया मार्क करें',
        table_orders: 'टेबल के आदेश',
        table_orders_desc: 'QR Menu से लाइव ऑर्डर प्रबंधित करें',
        gst_tax_settings: 'GST / टैक्स सेटिंग्स',
        enable_global_gst: 'ग्लोबल GST सिस्टम सक्षम करें',
        gst_add_desc: 'हर ऑर्डर पर {rate}% GST जोड़ा जाएगा',
        per_product_gst: 'प्रति उत्पाद GST',
        default_gst_desc: 'हमेशा सभी उत्पादों के लिए डिफ़ॉल्ट GST का उपयोग करें',
        quick_select_rate: 'त्वरित दर चुनें',
        custom_rate: 'कस्टम दर (%)',
        enable_discounts_label: 'छूट सक्षम करें',
        allow_discount_desc: 'बिल बनाते समय छूट फ़ील्ड की अनुमति दें',
        default_discount_label: 'डिफ़ॉल्ट छूट दर',
        discount_rate: 'छूट दर',
        enable_service_charge_label: 'सर्विस चार्ज सक्षम करें',
        service_charge_desc: 'बिलों में सर्विस चार्ज जोड़ें (जैसे, डिलीवरी)',
        default_service_charge_label: 'डिफ़ॉल्ट सर्विस चार्ज',
        kot_feature_title: 'KOT (किचन ऑर्डर टिकट)',
        kot_feature_desc: 'KOT बिलिंग और टेबल बुकिंग सुविधाओं को प्रबंधित करें',
        enable_kot_billing: 'KOT बिलिंग सक्षम करें',
        enable_kot_desc: 'त्वरित ऑर्डर के लिए किचन ऑर्डर टिकट बनाने की अनुमति दें',
        enable_table_booking: 'टेबल बुकिंग सक्षम करें',
        enable_table_booking_desc: 'KOT ऑर्डर के लिए टेबल नंबर असाइन करें',
        kot_info_text: 'KOT बटन त्वरित बिल स्क्रीन में दिखाई देगा। अंतिम बिलिंग से पहले किचन ऑर्डर प्रिंट करने के लिए इसका उपयोग करें।',
        item_name_placeholder: 'जैसे: बर्गर, पिज्जा...',
        choose_category: 'कैटेगरी चुनें',
        select_category_for_item: 'अपने आइटम के लिए कैटेगरी चुनें',
        no_categories_found: 'मेनू में कोई कैटेगरी नहीं मिली।',
        item_added_desc: 'आइटम मेनू में जोड़ दिया गया है।',
        category_added_to_list: 'कैटेगरी स्थानीय सूची में जोड़ दी गई है।',
        no_tables_created: 'अभी तक कोई टेबल नहीं बनाई गई है',
        get_started_create_table: 'शुरू करें: टेबल बनाएं',
    },
    pa: {
        settings: 'ਸੈਟਿੰਗਾਂ',
        manage_account: 'ਆਪਣੇ ਖਾਤੇ ਅਤੇ ਪਸੰਦਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ',
        app_features: 'ਐਪ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
        select_language: 'ਭਾਸ਼ਾ ਚੁਣੋ',
        kot_tables: 'KOT ਅਤੇ ਟੇਬਲ',
        kitchen_orders: 'ਰਸੋਈ ਆਰਡਰ ਟਿਕਟ (KOT), ਟੇਬਲ ਬੁਕਿੰਗ',
        change_language_desc: 'ਐਪ ਦੀ ਭਾਸ਼ਾ ਪੰਜਾਬੀ, ਅੰਗਰੇਜ਼ੀ ਆਦਿ ਵਿੱਚ ਬਦਲੋ',
        success_update: 'ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਕੀਤਾ ਗਿਆ!',
        done: 'ਹੋ ਗਿਆ',
        menu: 'ਮੇਨੂ',
        orders: 'ਆਰਡਰ',
        dashboard: 'ਡੈਸ਼ਬੋਰਡ',
        printer: 'ਪ੍ਰਿੰਟਰ',
        client: 'ਗਾਹਕ',
        add_item: 'ਆਈਟਮ ਜੋੜੋ',
        total: 'ਕੁੱਲ',
        cart: 'ਕਾਰਟ',
        checkout: 'ਚੈੱਕਆਊਟ',
        paying: 'ਭੁਗਤਾਨ',
        received: 'ਪ੍ਰਾਪਤ',
        cash: 'ਨਕਦ',
        upi: 'UPI',
        card: 'ਕਾਰਡ',
        items: 'ਆਈਟਮਾਂ',
        price: 'ਕੀਮਤ',
        quantity: 'ਮਾਤਰਾ',
        bill: 'ਬਿੱਲ',
        save: 'ਸੇਵ ਕਰੋ',
        print: 'ਪ੍ਰਿੰਟ ਕਰੋ',
        hold: 'ਹੋਲਡ ਕਰੋ',
        clear: 'ਸਾਫ ਕਰੋ',
        loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
        no_items: 'ਕੋਈ ਆਈਟਮ ਨਹੀਂ ਮਿਲੀ',
        search: 'ਖੋਜੋ...',
        live_orders: 'ਲਾਈਵ ਆਰਡਰ',
        tap_table: 'ਆਰਡਰ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰਨ ਲਈ ਟੇਬਲ \'ਤੇ ਟੈਪ ਕਰੋ',
        add_table: 'ਟੇਬਲ ਜੋੜੋ',
        active_orders: 'ਸਰਗਰਮ ਆਰਡਰ',
        no_active_orders: 'ਕੋਈ ਸਰਗਰਮ ਆਰਡਰ ਨਹੀਂ',
        quick_add_table: 'ਫਟਾਫਟ ਟੇਬਲ ਜੋੜੋ',
        table_name: 'ਟੇਬਲ ਦਾ ਨਾਮ',
        cancel: 'ਰੱਦ ਕਰੋ',
        create: 'ਬਣਾਓ',
        sales_summary: 'ਵਿਕਰੀ ਸਾਰ',
        today: 'ਅੱਜ',
        weekly: 'ਹਫਤਾਵਾਰੀ',
        monthly: 'ਮਹੀਨਾਵਾਰ',
        analytics_reports: 'ਵਿਸ਼ਲੇਸ਼ਣ ਅਤੇ ਰਿਪੋਰਟਾਂ',
        daily_sales: 'ਰੋਜ਼ਾਨਾ ਵਿਕਰੀ',
        weekly_sales: 'ਹਫਤਾਵਾਰੀ ਵਿਕਰੀ',
        monthly_sales: 'ਮਹੀਨਾਵਾਰ ਵਿਕਰੀ',
        bill_records: 'ਬਿੱਲ ਰਿਕਾਰਡ',
        performance: 'ਅੱਜ ਦੀ ਕਾਰਗੁਜ਼ਾਰੀ',
        trends: '7-ਦਿਨ ਦੇ ਰੁਝਾਨ',
        growth: 'ਮਾਸਿਕ ਵਾਧਾ ਸਮੀਖਿਆ',
        invoices: 'ਸਾਰੇ ਪੁਰਾਣੇ ਇਨਵੌਇਸ',
        parties: 'ਪਾਰਟੀਆਂ',
        categories: 'ਸ਼੍ਰੇਣੀਆਂ',
        add_customer: 'ਗਾਹਕ ਜੋੜੋ',
        no_customers: 'ਕੋਈ ਗਾਹਕ ਨਹੀਂ ਮਿਲਿਆ',
        regular_billing: 'ਨਿਯਮਤ ਬਿਲਿੰਗ',
        address: 'ਬਿਲਿੰਗ ਪਤਾ',
        balance: 'ਮੌਜੂਦਾ ਬਕਾਇਆ',
        call: 'ਕਾਲ',
        whatsapp: 'ਵਟਸਐਪ',
        regular: 'ਨਿਯਮਤ',
        welcome_guest: 'ਜੀ ਆਇਆਂ ਨੂੰ ਮਹਿਮਾਨ',
        hi: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ',
        home: 'ਹੋਮ',
        home_menu: 'ਹੋਮ ਮੇਨੂ',
        table_qr_codes: 'ਟੇਬਲ QR ਕੋਡ',
        edit_menu_item: 'ਮੇਨੂ ਆਈਟਮ ਐਡਿਟ ਕਰੋ',
        sign_in: 'ਸਾਈਨ ਇਨ',
        sign_out: 'ਸਾਈਨ ਆਊਟ',
        edit_item: 'ਆਈਟਮ ਐਡਿਟ ਕਰੋ',
        add_new_item: 'ਨਵੀਂ ਆਈਟਮ ਜੋੜੋ',
        add_category: 'ਸ਼੍ਰੇਣੀ ਜੋੜੋ',
        items_list: 'ਆਈਟਮ ਸੂਚੀ',
        qr_header: 'ਟੇਬਲ QR ਕੋਡ',
        business_name: 'ਵਪਾਰ ਦਾ ਨਾਮ',
        business_address: 'ਵਪਾਰ ਦਾ ਪਤਾ',
        gst_number: 'GST ਨੰਬਰ',
        save_profile: 'ਪ੍ਰੋਫਾਈਲ ਸੇਵ ਕਰੋ',
        profile_saved: 'ਪ੍ਰੋਫਾਈਲ ਸੇਵ ਹੋ ਗਈ!',
        daily_report: 'ਰੋਜ਼ਾਨਾ ਵਿਕਰੀ ਰਿਪੋਰਟ',
        weekly_report: 'ਹਫਤਾਵਾਰੀ ਵਿਕਰੀ ਰਿਪੋਰਟ',
        monthly_report: 'ਮਹੀਨਾਵਾਰ ਵਿਕਰੀ ਰਿਪੋਰਟ',
        all_transactions: 'ਸਾਰੇ ਲੈਣ-ਦੇਣ',
        hold_orders: 'ਹੋਲਡ ਆਰਡਰ',
        no_hold_orders: 'ਕੋਈ ਹੋਲਡ ਆਰਡਰ ਨਹੀਂ',
        bill_details: 'ਬਿੱਲ ਦਾ ਵੇਰਵਾ',
        print_bill: 'ਬਿੱਲ ਪ੍ਰਿੰਟ ਕਰੋ',
        gst_vat: 'GST/VAT',
        discounts: 'ਛੋਟਾਂ (Discounts)',
        app_features_desc: 'ਇੱਥੇ ਐਪ ਦੀਆਂ ਸਾਰੀਆਂ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ',
        bill_branding: 'ਆਪਣੇ ਬਿੱਲਾਂ ਵਿੱਚ ਬ੍ਰਾਂਡਿੰਗ ਜੋੜੋ',
        qr_menu: 'QR ਮੇਨੂ',
        manage_live_orders: 'ਲਾਈਵ ਆਰਡਰ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ',
        edit_profile: 'ਬਿਜ਼ਨਸ ਪ੍ਰੋਫਾਈਲ ਐਡਿਟ ਕਰੋ',
        create_profile: 'ਬਿਜ਼ਨਸ ਪ੍ਰੋਫਾਈਲ ਬਣਾਓ',
        setup_profile: 'ਆਪਣਾ ਪੇਸ਼ੇਵਰ ਬਿਜ਼ਨਸ ਪ੍ਰੋਫਾਈਲ ਸੈੱਟ ਕਰੋ',
        bills_transactions: 'ਬਿੱਲ ਅਤੇ ਲੈਣ-ਦੇਣ',
        gst_vat_discounts: 'GST/VAT ਅਤੇ ਛੋਟਾਂ',
        business_profile: 'ਬਿਜ਼ਨਸ ਪ੍ਰੋਫਾਈਲ',
        advance_loyalty: 'ਐਡਵਾਂਸ ਲਾਇਲਟੀ',
        points_system: 'ਪੁਆਇੰਟਸ ਸਿਸਟਮ, ਗਾਹਕ ਲਾਇਲਟੀ',
        kot_billing: 'KOT ਅਤੇ ਬਿਲਿੰਗ',
        edit_category: 'ਆਈਟਮ ਸ਼੍ਰੇਣੀ ਐਡਿਟ ਕਰੋ',
    },
    gu: {
        settings: 'સેટિંગ્સ',
        manage_account: 'તમારા એકાઉન્ટ અને પસંદગીઓનું સંચાલન કરો',
        app_features: 'એપ્લિકેશન સુવિધાઓ',
        select_language: 'ભાષા પસંદ કરો',
        kot_tables: 'KOT અને ટેબલ્સ',
        kitchen_orders: 'કિચન ઓર્ડર ટિકિટ (KOT), ટેબલ બુકિંગ',
        change_language_desc: 'એપ્લિકેશન ભાષા ગુજરાતી, અંગ્રેજી વગેરેમાં બદલો',
        success_update: 'સફળતાપૂર્વક અપડેટ થયું!',
        done: 'થઈ ગયું',
        menu: 'મેનુ',
        orders: 'ઓર્ડર',
        dashboard: 'ડેશબોર્ડ',
        printer: 'પ્રિન્ટર',
        client: 'ગ્રાહક',
        add_item: 'આઇટમ ઉમેરો',
        total: 'કુલ',
        cart: 'કાર્ટ',
        checkout: 'ચેકઆઉટ',
        paying: 'ચુકવણી',
        received: 'પ્રાપ્ત',
        cash: 'રોકડ',
        upi: 'UPI',
        card: 'કાર્ડ',
        items: 'આઇટમ્સ',
        price: 'કિંમત',
        quantity: 'જથ્થો',
        bill: 'બિલ',
        save: 'સાચવો',
        print: 'પ્રિન્ટ',
        hold: 'હોલ્ડ',
        clear: 'સાફ કરો',
        loading: 'લોડ થઈ રહ્યું છે...',
        no_items: 'કોઈ આઇટમ મળી નથી',
        search: 'શોધો...',
        live_orders: 'લાઇવ ઓર્ડર',
        tap_table: 'ઓર્ડર સંચાલિત કરવા માટે ટેબલ પર ટેપ કરો',
        add_table: 'ટેબલ ઉમેરો',
        active_orders: 'સક્રિય ઓર્ડર',
        no_active_orders: 'કોઈ સક્રિય ઓર્ડર નથી',
        quick_add_table: 'ઝડપી ટેબલ ઉમેરો',
        table_name: 'ટેબલ નામ',
        cancel: 'રદ કરો',
        create: 'બનાવો',
        sales_summary: 'વેચાણ સારાંશ',
        today: 'આજે',
        weekly: 'સાપ્તાહિક',
        monthly: 'માસિક',
        analytics_reports: 'એનાલિટિક્સ અને રિપોર્ટ્સ',
        daily_sales: 'દૈનિક વેચાણ',
        weekly_sales: 'સાપ્તાહિક વેચાણ',
        monthly_sales: 'માસિક વેચાણ',
        bill_records: 'બિલ રેકોર્ડ્સ',
        performance: 'આજના પ્રદર્શન',
        trends: '7-દિવસના વલણો',
        growth: 'માસિક વૃદ્ધિ અવલોકન',
        invoices: 'તમામ ઐતિહાસિક ઇન્વૉઇસેસ',
        parties: 'પાર્ટીઓ',
        categories: 'કેટેગરીઝ',
        add_customer: 'ગ્રાહક ઉમેરો',
        no_customers: 'કોઈ ગ્રાહક મળ્યા નથી',
        regular_billing: 'નિયમિત બિલિંગ',
        address: 'બિલિંગ સરનામું',
        balance: 'વર્તમાન બેલેન્સ',
        call: 'કૉલ',
        whatsapp: 'વોટ્સએપ',
        regular: 'નિયમિત',
        welcome_guest: 'સ્વાગત મહેમાન',
        hi: 'નમસ્તે',
        home: 'હોમ',
        home_menu: 'હોમ મેનુ',
        table_qr_codes: 'ટેબલ QR કોડ',
        edit_menu_item: 'મેનુ આઇટમ એડિટ કરો',
        sign_in: 'સાઇન ઇન',
        sign_out: 'સાઇન આઉટ',
        edit_item: 'આઇટમ એડિટ કરો',
        add_new_item: 'નવી આઇટમ ઉમેરો',
        add_category: 'કેટેગરી ઉમેરો',
        items_list: 'આઇટમ લિસ્ટ',
        qr_header: 'ટેબલ QR કોડ',
        business_name: 'વ્યવસાયનું નામ',
        business_address: 'વ્યવસાય સરનામું',
        gst_number: 'GST નંબર',
        save_profile: 'પ્રોફાઇલ સાચવો',
        profile_saved: 'પ્રોફાઇલ સાચવવામાં આવી!',
        daily_report: 'દૈનિક વેચાણ રિપોર્ટ',
        weekly_report: 'સાપ્તાહિક વેચાણ રિપોર્ટ',
        monthly_report: 'માસિક વેચાણ રિપોર્ટ',
        all_transactions: 'તમામ વ્યવહારો',
        hold_orders: 'હોલ્ડ ઓર્ડર્સ',
        no_hold_orders: 'કોઈ હોલ્ડ ઓર્ડર નથી',
        bill_details: 'બિલ વિગતો',
        print_bill: 'બિલ પ્રિન્ટ કરો',
        gst_vat: 'GST/VAT',
        discounts: 'ડિસ્કાઉન્ટ (Discounts)',
        app_features_desc: 'અહીં બધી એપ્લિકેશન સુવિધાઓ મેનેજ કરો',
        bill_branding: 'તમારા બિલોમાં બ્રાન્ડિંગ ઉમેરો',
        qr_menu: 'QR મેનુ',
        manage_live_orders: 'લાઇવ ઓર્ડર મેનેજ કરો',
        edit_profile: 'બિઝનેસ પ્રોફાઇલ એડિટ કરો',
        create_profile: 'બિઝનેસ પ્રોફાઇલ બનાવો',
        setup_profile: 'તમારી વ્યાવસાયિક બિઝનેસ પ્રોફાઇલ સેટ કરો',
        bills_transactions: 'બિલ અને વ્યવહારો',
        gst_vat_discounts: 'GST/VAT અને ડિસ્કાઉન્ટ',
        business_profile: 'બિઝનેસ પ્રોફાઇલ',
        advance_loyalty: 'એડવાન્સ લોયલ્ટી',
        points_system: 'પોઈન્ટ્સ સિસ્ટમ, ગ્રાહક લોયલ્ટી',
        kot_billing: 'KOT અને બિલિંગ',
        edit_category: 'આઇટમ કેટેગરી એડિટ કરો',
    },
    mr: {
        settings: 'सेटिंग्ज',
        manage_account: 'तुमचे खाते आणि प्राधान्ये व्यवस्थापित करा',
        app_features: 'अॅप वैशिष्ट्ये',
        select_language: 'भाषा निवडा',
        kot_tables: 'KOT आणि टेबल',
        kitchen_orders: 'किचन ऑर्डर तिकिटे (KOT), टेबल बुकिंग',
        change_language_desc: 'अॅपची भाषा मराठी, इंग्रजी इत्यादीमध्ये बदला',
        success_update: 'यशस्वीरित्या अपडेट केले!',
        done: 'झाले',
        menu: 'मेनू',
        orders: 'ऑर्डर',
        dashboard: 'डॅशबोर्ड',
        printer: 'प्रिंटर',
        client: 'ग्राहक',
        add_item: 'आयटम जोडा',
        total: 'एकूण',
        cart: 'कार्ट',
        checkout: 'चेकआउट',
        paying: 'पेमेंट',
        received: 'प्राप्त',
        cash: 'रोख',
        upi: 'UPI',
        card: 'कार्ड',
        items: 'आयटम',
        price: 'किंमत',
        quantity: 'प्रमाण',
        bill: 'बिल',
        save: 'जतन करा',
        print: 'प्रिंट',
        hold: 'होल्ड',
        clear: 'क्लिअर करा',
        loading: 'लोड होत आहे...',
        no_items: 'कोणतेही आयटम सापडले नाहीत',
        search: 'शोधा...',
        live_orders: 'लाईव्ह ऑर्डर्स',
        tap_table: 'ऑर्डर्स व्यवस्थापित करण्यासाठी टेबलवर टॅप करा',
        add_table: 'टेबल जोडा',
        active_orders: 'सक्रिय ऑर्डर्स',
        no_active_orders: 'कोणतीही सक्रिय ऑर्डर नाही',
        quick_add_table: 'त्वरित टेबल जोडा',
        table_name: 'टेबलचे नाव',
        cancel: 'रद्द करा',
        create: 'तयार करा',
        sales_summary: 'विक्री सारांश',
        today: 'आज',
        weekly: 'साप्ताहिक',
        monthly: 'मासिक',
        analytics_reports: 'विश्लेषण आणि अहवाल',
        daily_sales: 'दैनिक विक्री',
        weekly_sales: 'साप्ताहिक विक्री',
        monthly_sales: 'मासिक विक्री',
        bill_records: 'बिल रेकॉर्ड',
        performance: 'आजची कामगिरी',
        trends: '7-दिवसांचे ट्रेंड',
        growth: 'मासिक वाढ विहंगावलोकन',
        invoices: 'सर्व ऐतिहासिक इनव्हॉइसेस',
        parties: 'पार्ट्या',
        categories: 'कॅटेगरी',
        add_customer: 'ग्राहक जोडा',
        no_customers: 'कोणीही ग्राहक सापडले नाहीत',
        regular_billing: 'नियमित बिलिंग',
        address: 'बिलिंग पत्ता',
        balance: 'चालू शिल्लक',
        call: 'कॉल',
        whatsapp: 'व्हॉट्सअॅप',
        regular: 'नियमित',
        welcome_guest: 'स्वागत पाहुणे',
        hi: 'नमस्कार',
        home: 'होम',
        home_menu: 'होम मेनू',
        table_qr_codes: 'टेबल QR कोड',
        edit_menu_item: 'मेनू घटक एडिट करा',
        sign_in: 'साइन इन',
        sign_out: 'साइन आउट',
        edit_item: 'आयटम एडिट करा',
        add_new_item: 'नवीन आयटम जोडा',
        add_category: 'कॅटेगरी जोडा',
        items_list: 'आयटम लिस्ट',
        qr_header: 'टेबल QR कोड',
        business_name: 'व्यावसायाचे नाव',
        business_address: 'व्यावसायाचा पत्ता',
        gst_number: 'GST नंबर',
        save_profile: 'प्रोफाइल जतन करा',
        profile_saved: 'प्रोफाइल जतन केली!',
        daily_report: 'दैनिक विक्री अहवाल',
        weekly_report: 'साप्ताहिक विक्री अहवाल',
        monthly_report: 'मासिक विक्री अहवाल',
        all_transactions: 'सर्व व्यवहार',
        hold_orders: 'होल्ड ऑर्डर्स',
        no_hold_orders: 'कोणताही होल्ड ऑर्डर नाही',
        bill_details: 'बिल तपशील',
        print_bill: 'बिल प्रिंट करा',
        gst_vat: 'GST/VAT',
        discounts: 'सवलत (Discounts)',
        app_features_desc: 'येथे सर्व अॅप वैशिष्ट्ये व्यवस्थापित करा',
        bill_branding: 'तुमच्या बिलांमध्ये ब्रँडिंग जोडा',
        qr_menu: 'QR मेनू',
        manage_live_orders: 'लाईव्ह ऑर्डर्स व्यवस्थापित करा',
        edit_profile: 'बिझनेस प्रोफाइल एडिट करा',
        create_profile: 'बिझनेस प्रोफाइल तयार करा',
        setup_profile: 'तुमचे व्यावसायिक बिझनेस प्रोफाइल सेट करा',
        bills_transactions: 'बिल आणि व्यवहार',
        gst_vat_discounts: 'GST/VAT आणि सवलती',
        business_profile: 'बिझनेस प्रोफाइल',
        advance_loyalty: 'एडवांस लॉयल्टी',
        points_system: 'पॉइंट्स सिस्टम, ग्राहक लॉयल्टी',
        kot_billing: 'KOT आणि बिलिंग',
        edit_category: 'आयटम कॅटेगरी एडिट करा',
    },
    ta: {
        settings: 'அமைப்புகள்',
        manage_account: 'உங்கள் கணக்கு and விருப்பங்களை நிர்வகிக்கவும்',
        app_features: 'ஆப் அம்சங்கள்',
        select_language: 'மொழியைத் தேர்ந்தெடுக்கவும்',
        kot_tables: 'KOT மற்றும் டேபிள்கள்',
        kitchen_orders: 'சமையலறை ஆர்டர் டிக்கெட்டுகள் (KOT), டேபிள் முன்பதிவு',
        change_language_desc: 'ஆப் மொழியை தமிழ், ஆங்கிலம் போன்றவற்றுக்கு மாற்றவும்',
        success_update: 'வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
        done: 'முடிந்தது',
        menu: 'மெனு',
        orders: 'ஆர்டர்கள்',
        dashboard: 'டாஷ்போர்டு',
        printer: 'பிரிண்டர்',
        client: 'வாடிக்கையாளர்',
        add_item: 'பொருளைச் சேர்',
        total: 'மொத்தம்',
        cart: 'கார்ட்',
        checkout: 'செக் அவுட்',
        paying: 'பணம் செலுத்துதல்',
        received: 'பெறப்பட்டது',
        cash: 'பணம்',
        upi: 'UPI',
        card: 'கார்டு',
        items: 'பொருட்கள்',
        price: 'விலை',
        quantity: 'அளவு',
        bill: 'பில்',
        save: 'சேமி',
        print: 'அச்சிடு',
        hold: 'பிடி',
        clear: 'அழி',
        loading: 'ஏற்றப்படுகிறது...',
        no_items: 'பொருட்கள் எதுவும் கிடைக்கவில்லை',
        search: 'தேடு...',
        live_orders: 'நேரடி ஆர்டர்கள்',
        tap_table: 'ஆர்டர்களை நிர்வகிக்க டேபிளைத் தட்டவும்',
        add_table: 'டேபிளைச் சேர்',
        active_orders: 'செயலில் உள்ள ஆர்டர்கள்',
        no_active_orders: 'செயலில் உள்ள ஆர்டர்கள் இல்லை',
        quick_add_table: 'விரைவான டேபிள் சேர்ப்பு',
        table_name: 'டேபிள் பெயர்',
        cancel: 'ரத்து செய்',
        create: 'உருவாக்கு',
        sales_summary: 'விற்பனை சுருக்கம்',
        today: 'இன்று',
        weekly: 'வாராந்திர',
        monthly: 'மாதாந்திர',
        analytics_reports: 'பகுப்பாய்வு மற்றும் அறிக்கைகள்',
        daily_sales: 'தினசரி விற்பனை',
        weekly_sales: 'வாராந்திர விற்பனை',
        monthly_sales: 'மாதாந்திர விற்பனை',
        bill_records: 'பில் பதிவுகள்',
        performance: 'இன்றைய செயல்திறன்',
        trends: '7-நாள் வருவாய் போக்குகள்',
        growth: 'மாதாந்திர வளர்ச்சி கண்ணோட்டம்',
        invoices: 'அனைத்து வரலாற்று விலைப்பட்டியல்கள்',
        parties: 'தரப்பினர்',
        categories: 'வகைகள்',
        add_customer: 'வாடிக்கையாளரைச் சேர்',
        no_customers: 'வாடிக்கையாளர்கள் யாரும் காணப்படவில்லை',
        regular_billing: 'வழக்கமான பில்லிங்',
        address: 'பில்லிங் முகவரி',
        balance: 'தற்போதைய இருப்பு',
        call: 'அழை',
        whatsapp: 'வாட்ஸ்அப்',
        regular: 'வழக்கமான',
        welcome_guest: 'விருந்தினரை வரவேற்கிறோம்',
        hi: 'வணக்கம்',
        home: 'முகப்பு',
        home_menu: 'முகப்பு மெனு',
        table_qr_codes: 'டேபிள் QR குறியீடுகள்',
        edit_menu_item: 'மெனு உருப்படியைத் திருத்து',
        sign_in: 'உள்நுழை',
        sign_out: 'வெளியேறு',
        edit_item: 'உருப்படியைத் திருத்து',
        add_new_item: 'புதிய உருப்படியைச் சேர்',
        add_category: 'வகையைச் சேர்',
        items_list: 'பொருட்களின் பட்டியல்',
        qr_header: 'டேபிள் QR குறியீடுகள்',
        business_name: 'வணிகப் பெயர்',
        business_address: 'வணிக முகவரி',
        gst_number: 'GST எண்',
        save_profile: 'விவரங்களைச் சேமி',
        profile_saved: 'சுயவிவரம் சேமிக்கப்பட்டது!',
        daily_report: 'தினசரி விற்பனை அறிக்கை',
        weekly_report: 'வாராந்திர விற்பனை அறிக்கை',
        monthly_report: 'மாதாந்திர விற்பனை அறிக்கை',
        all_transactions: 'அனைத்து பரிவர்த்தனைகள்',
        hold_orders: 'பிடிக்கப்பட்ட ஆர்டர்கள்',
        no_hold_orders: 'பிடிக்கப்பட்ட ஆர்டர்கள் இல்லை',
        bill_details: 'பில் விவரங்கள்',
        print_bill: 'பில் அச்சிடு',
        gst_vat: 'GST/VAT',
        discounts: 'தள்ளுபடிகள் (Discounts)',
        app_features_desc: 'அனைத்து பயன்பாட்டு அம்சங்களையும் இங்கே நிர்வகிக்கவும்',
        bill_branding: 'உங்கள் பில்களில் பிராண்டிங் சேர்க்கவும்',
        qr_menu: 'QR மெனு',
        manage_live_orders: 'நேரடி ஆர்டர்களை நிர்வகிக்கவும்',
        edit_profile: 'வணிகச் சுயவிவரத்தைத் திருத்தவும்',
        create_profile: 'வணிகச் சுயவிவரத்தை உருவாக்கவும்',
        setup_profile: 'உங்கள் நிபுணத்துவ வணிகச் சுயவிவரத்தை அமைக்கவும்',
        bills_transactions: 'பில்கள் மற்றும் பரிவர்த்தனைகள்',
        gst_vat_discounts: 'GST/VAT & தள்ளுபடிகள்',
        business_profile: 'வணிகச் சுயவிவரம்',
        advance_loyalty: 'அட்வான்ஸ் லாயல்டி',
        points_system: 'புள்ளிகள் அமைப்பு, வாடிக்கையாளர் லாயல்டி',
        kot_billing: 'KOT & பில்லிங்',
        edit_category: 'பொருள் வகையைத் திருத்து',
    },
    te: {
        settings: 'సెట్టింగ్‌లు',
        manage_account: 'మీ ఖాతా మరియు ప్రాధాన్యతలను నిర్వహించండి',
        app_features: 'యాప్ ఫీచర్లు',
        select_language: 'భాషను ఎంచుకోండి',
        kot_tables: 'KOT మరియు టేబుల్స్',
        kitchen_orders: 'వంటగది ఆర్డర్ టిక్కెట్లు (KOT), టేబుల్ బుకింగ్',
        change_language_desc: 'యాప్ భాషను తెలుగు, ఇంగ్లీష్ మొదలైన వాటికి మార్చండి',
        success_update: 'విజయవంతంగా నవీకరించబడింది!',
        done: 'పూర్తయింది',
        menu: 'మెను',
        orders: 'ఆర్డర్లు',
        dashboard: 'డాష్‌బోర్డ్',
        printer: 'ప్రింటర్',
        client: 'కస్టమర్',
        add_item: 'ఐటెమ్‌ను జోడించండి',
        total: 'మొత్తం',
        cart: 'కార్ట్',
        checkout: 'చెక్అవుట్',
        paying: 'చెల్లింపు',
        received: 'అందుకున్నారు',
        cash: 'నగదు',
        upi: 'UPI',
        card: 'కార్డ్',
        items: 'ఐటెమ్‌లు',
        price: 'ధర',
        quantity: 'పరిమాణం',
        bill: 'బిల్లు',
        save: 'సేవ్ చేయండి',
        print: 'ప్రింట్',
        hold: 'హోల్డ్',
        clear: 'క్లియర్ చేయండి',
        loading: 'లోడ్ అవుతోంది...',
        no_items: 'ఐటెమ్‌లు ఏవీ కనుగొనబడలేదు',
        search: 'వెతకండి...',
        live_orders: 'లైవ్ ఆర్డర్లు',
        tap_table: 'ఆర్డర్లను నిర్వహించడానికి టేబుల్‌పై నొక్కండి',
        add_table: 'టేబుల్‌ను జోడించండి',
        active_orders: 'యాక్టివ్ ఆర్డర్లు',
        no_active_orders: 'యాక్టివ్ ఆర్డర్లు ఏవీ లేవు',
        quick_add_table: 'త్వరిత టేబుల్ జోడింపు',
        table_name: 'టేబుల్ పేరు',
        cancel: 'రద్దు చేయండి',
        create: 'సృష్టించండి',
        sales_summary: 'విక్రయాల సారాంశం',
        today: 'నేడు',
        weekly: 'వారపు',
        monthly: 'నెలవారీ',
        analytics_reports: 'అనలిటిక్స్ & రిపోర్ట్స్',
        daily_sales: 'రోజువారీ విక్రయాలు',
        weekly_sales: 'వారపు విక్రయాలు',
        monthly_sales: 'నెలవారీ విక్రయాలు',
        bill_records: 'బిల్లు రికార్డులు',
        performance: 'నేటి పనితీరు',
        trends: '7-రోజుల ఆదాయ పోకడలు',
        growth: 'నెలవారీ వృద్ధి అవలోకనం',
        invoices: 'అన్ని చారిత్రక ఇన్‌వాయిస్‌లు',
        parties: 'పార్టీలు',
        categories: 'కేటగిరీలు',
        add_customer: 'కస్టమర్‌ను జోడించండి',
        no_customers: 'కస్టమర్‌లు ఎవరూ కనుగొనబడలేదు',
        regular_billing: 'రెగ్యులర్ బిల్లింగ్',
        address: 'బిల్లింగ్ చిరునామా',
        balance: 'ప్రస్తుత నిల్వ',
        call: 'కాల్',
        whatsapp: 'వాట్సాప్',
        regular: 'రెగ్యులర్',
        welcome_guest: 'స్వాగతం అతిథి',
        hi: 'నమస్కారం',
        home: 'హోమ్',
        home_menu: 'హోమ్ మెను',
        table_qr_codes: 'టేబుల్ QR కోడ్‌లు',
        edit_menu_item: 'మెను ఐటెమ్‌ను సవరించండి',
        sign_in: 'సైన్ ఇన్',
        sign_out: 'సైన్ అవుట్',
        edit_item: 'ఐటెమ్‌ను సవరించండి',
        add_new_item: 'కొత్త ఐటెమ్‌ను జోడించండి',
        add_category: 'కేటగిరీని జోడించండి',
        items_list: 'ఐటెమ్‌ల జాబితా',
        qr_header: 'టేబుల్ QR కోడ్‌లు',
        business_name: 'వ్యాపార పేరు',
        business_address: 'వ్యాపార చిరునామా',
        gst_number: 'GST సంఖ్య',
        save_profile: 'ప్రొఫైల్ సేవ్ చేయండి',
        profile_saved: 'ప్రొఫైల్ సేవ్ చేయబడింది!',
        daily_report: 'రోజువారీ విక్రయాల నివేదిక',
        weekly_report: 'వారపు విక్రయాల నివేదిక',
        monthly_report: 'నెలవారీ విక్రయాల నివేదిక',
        all_transactions: 'అన్ని లావాదేవీల',
        hold_orders: 'హోల్డ్ ఆర్డర్లు',
        no_hold_orders: 'హోల్డ్ ఆర్డర్లు ఏవీ లేవు',
        bill_details: 'బిల్లు వివరాలు',
        print_bill: 'బిల్లును ప్రింట్ చేయండి',
        gst_vat: 'GST/VAT',
        discounts: 'డిస్కౌంట్లు (Discounts)',
        app_features_desc: 'ఇక్కడ అన్ని అనువర్తన ఫీచర్‌లను నిర్వహించండి',
        bill_branding: 'మీ బిల్లులకు బ్రాండింగ్‌ను జోడించండి',
        qr_menu: 'QR మెను',
        manage_live_orders: 'లైవ్ ఆర్డర్‌లను నిర్వహించండి',
        edit_profile: 'బిజినెస్ ప్రొఫైల్‌ను సవరించండి',
        create_profile: 'బిజినెస్ ప్రొఫైల్‌ను సృష్టించండి',
        setup_profile: 'మీ వృత్తిపరమైన బిజినెస్ ప్రొఫైల్‌ను సెటప్ చేయండి',
        bills_transactions: 'బిల్లులు & లావాదేవీలు',
        gst_vat_discounts: 'GST/VAT & డిస్కౌంట్లు',
        business_profile: 'బిజినెస్ ప్రొఫైల్',
        advance_loyalty: 'అడ్వాన్స్ లాయల్టీ',
        points_system: 'పాయింట్ల వ్యవస్థ, కస్టమర్ లాయల్టీ',
        kot_billing: 'KOT & బిల్లింగ్',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<LanguageType>('en');

    useEffect(() => {
        loadLanguage();
    }, []);

    const loadLanguage = async () => {
        try {
            const savedLanguage = await AsyncStorage.getItem('app_language');
            if (savedLanguage) {
                setLanguageState(savedLanguage as LanguageType);
            }
        } catch (e) {
            console.error('Failed to load language', e);
        }
    };

    const setLanguage = async (lang: LanguageType) => {
        try {
            await AsyncStorage.setItem('app_language', lang);
            setLanguageState(lang);
        } catch (e) {
            console.error('Error saving language:', e);
        }
    };
 
    const t = (key: string, params?: Record<string, any>): string => {
        let text = translations[language]?.[key] || translations['en']?.[key] || key;
        
        if (params) {
            Object.keys(params).forEach(param => {
                text = text.replace(new RegExp(`{${param}}`, 'g'), params[param]);
            });
        }
        
        return text;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
